/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const get_bg_idx: () => number;
export const get_enemy_flash: () => number;
export const get_enemy_hp: () => number;
export const get_enemy_idx: () => number;
export const get_enemy_max_hp: () => number;
export const get_game_state: () => number;
export const get_player_flash: () => number;
export const get_player_hp: () => number;
export const get_player_level: () => number;
export const get_player_max_hp: () => number;
export const get_player_max_mp: () => number;
export const get_player_mp: () => number;
export const key_index: (a: number, b: number) => number;
export const set_key: (a: number, b: number) => void;
export const start_battle_from_js: (a: number) => void;
export const main: () => void;
export const main_aobacastle: () => void;
export const main_nanoteras: () => void;
export const wasm_bindgen_7409b725ef28e7cd___convert__closures_____invoke___web_sys_e2dca692cdd4c806___features__gen_MouseEvent__MouseEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_7409b725ef28e7cd___convert__closures_____invoke___web_sys_e2dca692cdd4c806___features__gen_MouseEvent__MouseEvent______true__1: (a: number, b: number, c: any) => void;
export const wasm_bindgen_7409b725ef28e7cd___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
