/// Constants - Color, Key, and other Pyxel constants
/// 
/// Re-exports all constants from pyxel-core

pub use pyxel::{
    // Colors
    COLOR_BLACK, COLOR_NAVY, COLOR_PURPLE, COLOR_GREEN, COLOR_BROWN, COLOR_DARK_BLUE,
    COLOR_LIGHT_BLUE, COLOR_WHITE, COLOR_RED, COLOR_ORANGE, COLOR_YELLOW, COLOR_LIME,
    COLOR_CYAN, COLOR_GRAY, COLOR_PINK, COLOR_PEACH,
    
    // Keys (Common)
    Key,
    KEY_ESCAPE, KEY_0, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9,
    KEY_MINUS, KEY_EQUALS, KEY_BACKSPACE, KEY_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y,
    KEY_U, KEY_I, KEY_O, KEY_P, KEY_LEFTBRACKET, KEY_RIGHTBRACKET, KEY_BACKSLASH,
    KEY_CAPSLOCK, KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L,
    KEY_SEMICOLON, KEY_QUOTE, KEY_RETURN, KEY_LSHIFT, KEY_Z, KEY_X, KEY_C, KEY_V,
    KEY_B, KEY_N, KEY_M, KEY_COMMA, KEY_PERIOD, KEY_SLASH, KEY_RSHIFT, KEY_ASTERISK,
    KEY_LALT, KEY_SPACE, KEY_RALT, KEY_LCTRL, KEY_RCTRL, KEY_INSERT,
    KEY_DELETE, KEY_HOME, KEY_END, KEY_PAGEUP, KEY_PAGEDOWN, KEY_UP, KEY_DOWN, KEY_LEFT,
    KEY_RIGHT, KEY_NUMLOCKCLEAR, KEY_KP_DIVIDE, KEY_KP_MULTIPLY, KEY_KP_MINUS, KEY_KP_PLUS, KEY_KP_DECIMAL,
    KEY_KP_ENTER, KEY_PAUSE, KEY_PRINTSCREEN, KEY_SCROLLLOCK, KEY_F1, KEY_F2, KEY_F3, KEY_F4,
    KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_F11, KEY_F12,
    
    // Mouse buttons
    MOUSE_BUTTON_LEFT, MOUSE_BUTTON_RIGHT, MOUSE_BUTTON_MIDDLE,
    MOUSE_POS_X, MOUSE_POS_Y, MOUSE_WHEEL_X, MOUSE_WHEEL_Y,
    
    // System constants
    VERSION, NUM_COLORS, NUM_IMAGES, IMAGE_SIZE, NUM_TILEMAPS, TILEMAP_SIZE,
    TILE_SIZE, DEFAULT_FPS, MAX_COLORS,
};
